"""
Data Models for COB Agent Prototype
Represents patient demographics, insurance coverage, and claims
"""

from dataclasses import dataclass, field
from datetime import datetime, date
from typing import List, Optional, Dict
from enum import Enum
import uuid


class InsuranceType(Enum):
    COMMERCIAL = "Commercial"
    MEDICARE = "Medicare"
    MEDICAID = "Medicaid"
    MEDICARE_ADVANTAGE = "Medicare Advantage"
    AUTO_INSURANCE = "Auto Insurance"
    WORKERS_COMP = "Workers Compensation"
    TRICARE = "Tricare"
    SELF_PAY = "Self Pay"


class ClaimStatus(Enum):
    SUBMITTED = "Submitted"
    DENIED = "Denied"
    PAID = "Paid"
    PENDING = "Pending"
    APPEALED = "Appealed"


class DenialReason(Enum):
    COB_MISSING = "COB Information Missing"
    WRONG_PRIMARY = "Wrong Primary Payer"
    MSP_VIOLATION = "Medicare Secondary Payer Violation"
    COORDINATION_PERIOD = "Coordination Period Issue"
    DEPENDENT_ELIGIBILITY = "Dependent Eligibility Issue"
    AUTO_LIABILITY = "Auto/Liability Not Primary"
    OTHER = "Other"


@dataclass
class Insurance:
    """Insurance coverage information"""
    insurance_id: str
    payer_name: str
    insurance_type: InsuranceType
    policy_number: str
    group_number: Optional[str]
    subscriber_id: str
    effective_date: date
    termination_date: Optional[date]
    is_primary: bool
    priority_order: int  # 1 = primary, 2 = secondary, etc.
    
    def is_active(self, service_date: date) -> bool:
        """Check if insurance is active on a given date"""
        if service_date < self.effective_date:
            return False
        if self.termination_date and service_date > self.termination_date:
            return False
        return True


@dataclass
class Patient:
    """Patient demographic and insurance information"""
    patient_id: str
    mrn: str  # Medical Record Number
    first_name: str
    last_name: str
    date_of_birth: date
    ssn_last_4: str
    address: str
    phone: str
    email: str
    insurance_coverage: List[Insurance] = field(default_factory=list)
    employment_status: Optional[str] = None
    spouse_employment: Optional[str] = None
    
    def get_age(self, reference_date: date = None) -> int:
        """Calculate patient age"""
        if reference_date is None:
            reference_date = date.today()
        age = reference_date.year - self.date_of_birth.year
        if reference_date.month < self.date_of_birth.month or \
           (reference_date.month == self.date_of_birth.month and 
            reference_date.day < self.date_of_birth.day):
            age -= 1
        return age
    
    def get_active_insurance(self, service_date: date) -> List[Insurance]:
        """Get all active insurance on a given date"""
        return [ins for ins in self.insurance_coverage if ins.is_active(service_date)]
    
    def get_primary_insurance(self, service_date: date) -> Optional[Insurance]:
        """Get primary insurance for a given date"""
        active = self.get_active_insurance(service_date)
        primary = [ins for ins in active if ins.is_primary]
        return primary[0] if primary else None


@dataclass
class Claim:
    """Medical claim information"""
    claim_id: str
    patient_id: str
    service_date: date
    admission_date: Optional[date]
    discharge_date: Optional[date]
    diagnosis_codes: List[str]
    procedure_codes: List[str]
    billed_amount: float
    primary_insurance_id: Optional[str]
    secondary_insurance_id: Optional[str]
    claim_status: ClaimStatus
    denial_reason: Optional[DenialReason]
    denial_date: Optional[date]
    submission_date: date
    paid_amount: float = 0.0
    notes: str = ""
    
    # Red flag indicators
    is_emergency: bool = False
    is_accident_related: bool = False
    is_work_related: bool = False
    has_third_party_liability: bool = False


@dataclass
class COBAlert:
    """COB issue alert generated by the agent"""
    alert_id: str
    claim_id: str
    patient_id: str
    alert_type: str
    severity: str  # HIGH, MEDIUM, LOW
    confidence_score: float  # 0-1
    detected_date: datetime
    description: str
    recommended_action: str
    data_points: Dict[str, any] = field(default_factory=dict)
    estimated_recovery: Optional[float] = None
    
    def __post_init__(self):
        if self.alert_id is None:
            self.alert_id = str(uuid.uuid4())
